language: node_js
node_js:
  - "5"
services:
  - mysql
before_script:
  - mysql -e 'create database IF NOT EXISTS mytest;'
  - mysql -e 'CREATE TABLE  `mytest`.`test` (`id` INT NOT NULL AUTO_INCREMENT ,`content` VARCHAR( 128 ) NOT NULL , PRIMARY KEY (`id`));'

